CREATE TABLE IF NOT EXISTS users(
    id int NOT NULL AUTO_INCREMENT,
    uid VARCHAR(255) NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    keypass VARCHAR(20) NOT NULL,
    birthday DATE NULL,
    profile_picture TEXT NULL,
    gender VARCHAR(50) NULL,
    level VARCHAR(20) NULL,
    is_active boolean default true,
    is_verify boolean default false,
    verify_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    is_newsletter boolean default false,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    last_login TIMESTAMP NULL DEFAULT NULL,
    fcm_id_mobile TEXT NULL,
    fcm_id_desktop TEXT NULL,
    PRIMARY KEY (id)
);
