CREATE TABLE IF NOT EXISTS payment_bank_accounts (
	id int NOT NULL AUTO_INCREMENT,
  bank VARCHAR(50) NOT NULL,
  account_number VARCHAR(100) NOT NULL,
  holder_name VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL,
  password VARBINARY NOT NULL,
  keypass VARCHAR(10) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,

  PRIMARY KEY (id)
);