CREATE TABLE IF NOT EXISTS product_details (
	id int NOT NULL AUTO_INCREMENT,
  product_id INT NOT NULL,
  size VARCHAR(50) NULL,
  color VARCHAR(50) NULL,
  stock INT DEFAULT 0,
  price FLOAT DEFAULT 0,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,

  PRIMARY KEY (id)
);