CREATE TABLE IF NOT EXISTS log_trx_apis (
	id int NOT NULL AUTO_INCREMENT,
  api TEXT NULL,
  request TEXT NULL,
  response TEXT NULL,
  header TEXT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id)
) 